spring:
  application:
    name: ai-agent
  ai:
    dashscope:
      api-key: ${API-KEY}
      chat:
        options:
          model: qwen3-coder-plus
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
#    ollama:
#      enabled: false
#      base-url: http://localhost:11434
#      chat:
#      model: gemma3:1b
#    vectorstore:
#      pgvector:
#        enabled: false
#        index-type: HNSW
#        #dimensions: 1536
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000
    mcp:
      client:
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
        sse:
          connections:
            server1:
              url: http://localhost:8127


#  datasource:
#    url: jdbc:postgresql://rm-cn-ioy4mn6ls0004k9o.rwlb.rds.aliyuncs.com/ai_agent
#    username: my_user
#    password:

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.fox.aiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchAPI
search-api:
  api-key: 9fF19y4uPvHKQLLXWh3WL7Yn
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG